# Generated by Django 2.0.6 on 2020-02-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sports',
            new_name='Sport',
        ),
    ]
