# Generated by Django 2.0.6 on 2020-02-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200219_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ['name'], 'verbose_name': 'Вид спорта', 'verbose_name_plural': 'Виды спорта'},
        ),
        migrations.AddField(
            model_name='sport',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='main/images', verbose_name='Изображение'),
        ),
    ]
