# Generated by Django 2.0.6 on 2020-02-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200220_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
    ]
