# Generated by Django 2.0.6 on 2020-02-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sport_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='secondimage',
            field=models.ImageField(blank=True, default='', upload_to='main/images', verbose_name='Изображение детальное'),
        ),
    ]
