# Generated by Django 2.0.6 on 2020-02-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sport_secondimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Событие')),
                ('image', models.ImageField(blank=True, default='', upload_to='main/images', verbose_name='Изображение')),
                ('secondimage', models.ImageField(blank=True, default='', upload_to='main/images', verbose_name='Изображение детальное')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('eventDate', models.DateField()),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['name'],
            },
        ),
    ]
