# Generated by Django 2.0.6 on 2020-02-24 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('image', models.ImageField(blank=True, default='', upload_to='main/images', verbose_name='Изображение')),
                ('slide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Sport')),
            ],
        ),
    ]
