# Generated by Django 2.0.6 on 2020-02-24 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sportslide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportslide',
            options={'ordering': ['name'], 'verbose_name': 'Блок для видов спорта', 'verbose_name_plural': 'Блоки для видов спорта'},
        ),
    ]
