# Generated by Django 2.0.6 on 2020-02-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200224_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportslide',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
