# Generated by Django 2.0.6 on 2020-02-24 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200224_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportslide',
            old_name='slide',
            new_name='sport',
        ),
    ]
