# Generated by Django 2.0.6 on 2020-02-25 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200224_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Sport'),
        ),
    ]
