# Generated by Django 2.0.6 on 2020-02-25 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_events_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='main/images', verbose_name='Изображение')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Events')),
            ],
            options={
                'verbose_name': 'Блок для событий',
                'verbose_name_plural': 'Блоки для событий',
                'ordering': ['id'],
            },
        ),
    ]
