# Generated by Django 2.0.6 on 2020-03-04 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200304_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadiums',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Sport'),
        ),
    ]
