# Generated by Django 2.0.6 on 2020-03-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_stadiums_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadiums',
            name='coordinates',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='stadiums',
            name='sport',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Виды спорта'),
        ),
    ]
