# Generated by Django 2.0.6 on 2020-03-08 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200304_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image1', models.ImageField(blank=True, default='', null=True, upload_to='main/images', verbose_name='Изображение1')),
                ('image2', models.ImageField(blank=True, default='', null=True, upload_to='main/images', verbose_name='Изображение2')),
                ('image3', models.ImageField(blank=True, default='', null=True, upload_to='main/images', verbose_name='Изображение3')),
                ('sort', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Sport')),
                ('stadium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Stadiums')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
                'ordering': ['id'],
            },
        ),
    ]
