# Generated by Django 2.0.6 on 2020-03-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_prices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prices',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='image3',
        ),
        migrations.AddField(
            model_name='prices',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
