# Generated by Django 2.0.6 on 2020-03-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200308_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='price',
        ),
        migrations.AddField(
            model_name='prices',
            name='price1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Цена за смену'),
        ),
        migrations.AddField(
            model_name='prices',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Цена за день'),
        ),
        migrations.AddField(
            model_name='prices',
            name='price3',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Цена за тренировку'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='main/images', verbose_name='Изображение'),
        ),
    ]
