# Generated by Django 2.0.6 on 2020-03-11 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200311_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['id'], 'verbose_name': 'Изображение слайдера', 'verbose_name_plural': 'Изображения слайдера'},
        ),
    ]
