# Generated by Django 2.0.6 on 2020-03-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200311_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
