# Generated by Django 2.0.6 on 2020-03-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_images_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadiums',
            name='imagebig',
        ),
        migrations.AddField(
            model_name='stadiums',
            name='video',
            field=models.TextField(blank=True, default='', verbose_name='Видео'),
        ),
    ]
