# Generated by Django 2.0.6 on 2020-03-16 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200311_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='more',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.More'),
        ),
    ]
