# Generated by Django 2.0.6 on 2020-03-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_events_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventslide',
            name='video',
            field=models.TextField(blank=True, default='', verbose_name='Видео'),
        ),
    ]
